#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-worker ]
do
  sleep 1
done

if [ ! -f /tmp/state/20-interface ]; then
	echo 'Initialization Complete' >/tmp/state/20-interface
fi


echo ''
echo '** [sentry] Starting Sentry Web Interface'
exec s6-setuidgid sentry sentry run web;
